/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.reavture;

import com.reavture.dao.UserDaoJDBC;
import com.reavture.models.User;
import io.javalin.Javalin;
import io.javalin.core.JavalinConfig;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {

    private static final Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {

        UserDaoJDBC daotest = new UserDaoJDBC();
        User u = daotest.readUserByUsername("jharnor0", "jharnor0@wiley.com");;
        u.setUsername("jharnor0");
        u.setPassword("jharnor0@wiley.com");
        logger.info(u.toString());


        try{
            Javalin server = Javalin.create(JavalinConfig::enableCorsForAllOrigins);
            server.start(8080);
        } catch (Exception e){
            throw new RuntimeException(e);
        }finally {
            logger.info("#2. Connection succeeded!");
        }
    }
}
