/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.revature;

import com.revature.dao.IUserDao;
import com.revature.dao.UserDaoJDBC;
import com.revature.models.User;
import com.revature.services.UserService;
import io.javalin.Javalin;
import io.javalin.core.JavalinConfig;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {

    private static final Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        IUserDao ud = new UserDaoJDBC();
        UserService us = new UserService(ud);
        User u = us.loginUser("jharnor0", "jharnor0@wiley.com");

        logger.info(u.toString());


        try{
            Javalin server = Javalin.create(JavalinConfig::enableCorsForAllOrigins);
            server.start(8080);
        } catch (Exception e){
            throw new RuntimeException(e);
        }finally {
            logger.info("#2. Connection succeeded!");
        }
    }
}
