/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.revature;

import com.revature.controllers.UserController;
import com.revature.dao.IUserDao;
import com.revature.dao.UserDaoJDBC;
import com.revature.models.User;
import com.revature.services.UserService;
import io.javalin.Javalin;
import io.javalin.core.JavalinConfig;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import static io.javalin.apibuilder.ApiBuilder.*;

public class App {

    private static final Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        IUserDao uDao = new UserDaoJDBC();
        UserService uService = new UserService(uDao);
        UserController uController = new UserController(uService);


        try{
            Javalin server = Javalin.create(JavalinConfig::enableCorsForAllOrigins);

            server.routes(()-> {
                path("employee", () -> {
                    post("/login", uController.handleLogin);
                    put("/update", uController.handleUpdate);
                    //put("/request", uController.handleReimbursementRequest);
                });
                path("manager", () -> {
                });
            });

            server.start(8080);
        } catch (Exception e){
            throw new RuntimeException(e);
        }finally {
            logger.info("#2. Connection succeeded!");
        }
    }
}
